<html>
<body>
Сообщает об исключениях, которые выбрасываются внутри блока <code>catch</code> без "обёртывания" пойманного исключения.
<p>Когда исключение выбрасывается в ответ на другое исключение, обёртывание исходного исключения предотвращает потерю важной контекстной информации, такой как кадры стека и номера строк.</p>
<p><b>Пример:</b></p>
<pre><code>
  ...
  catch (IOException e) {
    closeAllConnections();
    throw new ConnectException("Connection problem."); // Предупреждение: 'throw' в блоке 'catch' игнорирует пойманное исключение 'e'
  }
</code></pre>
<p>Настройка проверки:</p>
<ul>
  <li>Используйте опцию <b>Игнорировать, если используется результат метода исключения</b>, чтобы указать, должна ли проверка игнорировать исключения, аргументом которых является результат вызова метода исходного исключения, например <code>getMessage()</code>.</li>
  <li>Используйте опцию <b>Игнорировать, если выброшенное исключение не может обернуть исключение</b>, чтобы игнорировать операторы <code>throw</code>, выбрасывающие исключения без конструктора, принимающего параметр типа <code>Throwable</code>.</li>
</ul>
</body>
</html>
